#!/bin/bash -xe

# adjust kernel parameter
cat > /etc/sysctl.d/99-rke2.conf << EOF
# disable non-working ipv6 in OTC ECS
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
# cis benchmark hardening
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
EOF

sysctl -p /etc/sysctl.d/99-rke2.conf

# upgrade os (retry if network is not ready)
for i in 1 2 3 4 5; do
  apt-get update && break || sleep 10;
done
DEBIAN_FRONTEND=noninteractive apt-get -yq -o Dpkg::Options::="--force-confdef" upgrade

# prepare additional disk for etcd
if [ -e /dev/vdb ] ; then
  if [ ! -e /dev/vdb1 ] ; then
    printf "o\nn\np\n1\n\n\nw\n" | fdisk /dev/vdb
    mkfs.ext4 /dev/vdb1
  fi
  mkdir -p /var/lib/rancher/rke2/server/db
  mount /dev/vdb1 /var/lib/rancher/rke2/server/db
  if [ -z $(grep "vdb" /etc/fstab) ]; then
    echo "/dev/vdb1 /var/lib/rancher/rke2/server/db ext4 defaults 0 1" >> /etc/fstab
  fi
else
  echo "no /dev/vdb device, etcd data might be lost"
fi

# doing os hardening
# https://github.com/dev-sec/puppet-os-hardening

wget https://apt.puppetlabs.com/puppet-release-focal.deb
dpkg -i puppet-release-focal.deb || exit 1
rm -f puppet-release-focal.deb

apt-get update
apt-get -yq install puppet-agent

systemctl stop puppet
systemctl disable puppet
/opt/puppetlabs/bin/puppet module install hardening-os_hardening || exit 1

cat > hardening.pp << EOF
class { 'os_hardening':
  enable_ipv4_forwarding => true,
}
EOF

/opt/puppetlabs/bin/puppet apply hardening.pp || exit 1
rm -f hardening.pp

# prepare rke2 ha config
mkdir -p /etc/rancher/rke2
cat > /etc/rancher/rke2/config.yaml << EOF
server: https://${rancher_host}.${rancher_domain}:9345
token: ${token}
tls-san:
  - ${rancher_host}.${rancher_domain}
# node-taint:
#  - "CriticalAddonsOnly=true:NoExecute"
EOF

# install rke2 with etcd backend
if [ "${rke2_version}" == "latest" ] || [ "${rke2_version}" == "stable" ]; then
  curl -svfL4 --retry 100 https://get.rke2.io | INSTALL_RKE2_CHANNEL=${rke2_version} sh -
else
  curl -svfL4 --retry 100 https://get.rke2.io | INSTALL_RKE2_VERSION=${rke2_version} sh -
fi

# start rke2
systemctl enable rke2-server.service
systemctl start --no-block rke2-server.service

# extend env vars
cat >> /root/.bashrc << EOF
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export PATH=$PATH:/var/lib/rancher/rke2/bin
source  <(/var/lib/rancher/rke2/bin/kubectl completion bash)
EOF

# while join cluster
while [ ! -f  /var/lib/rancher/rke2/bin/kubectl ] ; do
  sleep 10
  echo "wait for kubectl"
done

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export PATH=$PATH:/var/lib/rancher/rke2/bin/

node_status=$(/var/lib/rancher/rke2/bin/kubectl get nodes | grep -i ready | wc -l)
while (( node_status < 1 )) ; do
  echo "wait for k8s is ready"
  systemctl stop rke2-server.service
  sleep 5
  rke2-killall.sh
  sleep 10
  systemctl start --no-block rke2-server.service
  sleep 30
  node_status=$(/var/lib/rancher/rke2/bin/kubectl get nodes | grep -i ready | wc -l)
done
